packages:
  - apps/*
  - packages/*

catalogs:
  # Development
  dev:
    '@cloudflare/workers-types': ^4.20251213.0
    '@tailwindcss/postcss': ^4
    '@types/node': ^24
    '@types/react': ^19
    '@types/react-dom': ^19
    drizzle-kit: ^0.31.8
    tailwindcss: ^4
    ts-patch: ^3.3.0
    tsdown: ^0.18.0
    typescript: ^5
    vitest: ^4.0.15
    wrangler: ^4.54.0

  # Backend
  backend:
    '@hono/zod-validator': ^0.7.5
    '@libsql/client': ^0.15.15
    '@react-email/components': ^1.0.1
    drizzle-orm: ^0.45.1
    hono: ^4.11.1
    resend: ^6.6.0
    winston: ^3.19.0
    winston-daily-rotate-file: ^5.0.0
    zod: ^4.2.0

  # Frontend
  frontend:
    '@next/third-parties': 16.0.10
    '@radix-ui/react-accordion': ^1.2.12
    '@radix-ui/react-dialog': ^1.1.15
    '@radix-ui/react-hover-card': ^1.1.15
    '@radix-ui/react-label': ^2.1.8
    '@radix-ui/react-popover': ^1.1.15
    '@radix-ui/react-progress': ^1.1.8
    '@radix-ui/react-scroll-area': ^1.2.10
    '@radix-ui/react-select': ^2.2.6
    '@radix-ui/react-separator': ^1.1.8
    '@radix-ui/react-slider': ^1.3.6
    '@radix-ui/react-slot': ^1.2.4
    '@radix-ui/react-tabs': ^1.1.13
    class-variance-authority: ^0.7.1
    clsx: ^2.1.1
    cmdk: ^1.1.1
    lucide-react: ^0.561.0
    next: 16.1.5
    next-themes: ^0.4.6
    ogl: ^1.0.11
    react: ^19
    react-dom: ^19
    react-dropzone: ^14.3.8
    sonner: ^2.0.7
    tailwind-merge: ^3.4.0
    tw-animate-css: ^1.4.0
