packages:
  - apps/*
  - packages/*
catalogs:
  dev:
    '@biomejs/biome': ^2.2.0
    '@cloudflare/workers-types': ^4.20250821.0
    '@tailwindcss/postcss': ^4
    '@types/node': ^22
    '@types/react': ^19
    '@types/react-dom': ^19
    drizzle-kit: ^0.31.4
    tailwindcss: ^4
    turbo: ^2.5.6
    typescript: ^5
    wrangler: ^4.31.0
  prod:
    '@hono/zod-validator': ^0.7.2
    '@libsql/client': ^0.15.12
    drizzle-orm: ^0.44.4
    hono: ^4.9.2
    next: 15.5.0
    react: ^19
    react-dom: ^19
    winston: ^3.17.0
    winston-daily-rotate-file: ^5.0.0
    zod: ^4.0.17
