packages:
  - apps/*
  - packages/*
catalogs:
  dev:
    '@cloudflare/workers-types': ^4.20251014.0
    '@tailwindcss/postcss': ^4
    '@types/node': ^24
    '@types/react': ^19
    '@types/react-dom': ^19
    drizzle-kit: ^0.31.6
    tailwindcss: ^4
    tsdown: ^0.16.0
    tw-animate-css: ^1.4.0
    typescript: ^5
    ts-patch: ^3.3.0
    wrangler: ^4.45.4
    vitest: ^4.0.7
  prod:
    '@hono/zod-validator': ^0.7.4
    '@libsql/client': ^0.15.15
    '@next/third-parties': 16.0.1
    '@react-email/components': ^0.5.1
    drizzle-orm: ^0.44.7
    hono: ^4.10.4
    lucide-react: ^0.552.0
    next-themes: ^0.4.6
    next: 16.0.1
    react: ^19
    react-dom: ^19
    react-dropzone: ^14.3.8
    resend: ^6.4.1
    tailwind-merge: ^3.3.1
    winston: ^3.18.3
    winston-daily-rotate-file: ^5.0.0
    zod: ^4.1.12
