packages:
  - apps/*
  - packages/*
catalogs:
  dev:
    '@biomejs/biome': ^2.2.0
    '@cloudflare/workers-types': ^4.20250821.0
    '@tailwindcss/postcss': ^4
    '@types/node': ^22
    '@types/react': ^19
    '@types/react-dom': ^19
    drizzle-kit: ^0.31.4
    tailwindcss: ^4
    turbo: ^2.5.6
    tsup: ^8.5.0
    tw-animate-css: ^1.3.7
    typescript: ^5
    ts-patch: ^3.3.0
    wrangler: ^4.31.0
  prod:
    '@hono/zod-validator': ^0.7.2
    '@libsql/client': ^0.15.12
    '@next/third-parties': 15.5.0
    '@react-email/components': ^0.5.1
    drizzle-orm: ^0.44.4
    hono: ^4.9.2
    lucide-react: ^0.540.0
    next-themes: ^0.4.6
    next: 15.5.0
    react: ^19
    react-dom: ^19
    resend: ^6.0.1
    tailwind-merge: ^3.3.1
    winston: ^3.17.0
    winston-daily-rotate-file: ^5.0.0
    zod: ^4.0.17
